require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - bin/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EachWithObject:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/Focus:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
